void main() {
  /* Değişkenler Ödev 1 */
  String sehir = "İstanbul";
  String ulke = "Türkiye";
  String telefon = "05055555555";
  int postaKodu = 34000;
  String email = "ornek@gmail.com";
  String meslek = "Mühendis";
  int stokMiktari = 500;
  String musteriAdi = "Koray";
  int bakiye = 5000;
  String dogumGunu = "Pazartesi";
  int maas = 10000;
  String medeniDurumu = "Bekar";
  String urunYorumu = "Ürün çok güzel";
  String odemeTarihi = "10.05.2002";
  String odeme = "Nakit";
  int siparisAdeti = 100;
  String arabaModeli = "Opel";
  String kitapAdi = "Flutter";
  String yayinlanmaTarihi = "15.10.2003";
  int indirimMiktari = 10;
  int odaSayisi = 15;
  int enlem = 36;
  int boylam = 45;
  String urunAdi = "ekmek";
  int yemekFiyati = 45;
  String marka = "Opel";
  String muzikAdi = "İsyan";
  String videoSuresi = "10 dk";
  int urunPuani = 10;
  String resimAdi = "Yağlı Boya";
  String dosyaFormati = ".jpg";
  const renk = "Mavi";
  const renkKodu = "0xFFFFFFFF";
  String telefonModeli = "Apple";
  String ekranBoyutu = "10.inc";
  int agirlik = 10;
  String ulusalGun = "23 Nisan Ulusal Egemenlik Ve Çocuk Bayramı";
  String tatilGunu = "Cumartesi";
  String rezervasyonTarihi = "10.05.2001";
  String stokAdi = "Araba";
  String otobusHatti = "Bakırköy - Zincirlikuyu";
  String kalanDakkika = "10 dk";
  int takipKodu = 1010101010;
  String kuponSuresi = "10 gün";
  int kuponKodu = 14141414;
  String faturaAdresi = "a mah. bilmemne sokak kat 8 daire: 35";

  print("Şehir : $sehir");
  print("Ülke : $ulke");
  print("Telefon : $telefon");
  print("Posta Kodu : $postaKodu");
  print("Email Adresi : $email");
  print("Mesleği : $meslek");
  print("Stok Miktarı : $stokMiktari");
  print("Müşteri Adı : $musteriAdi");
  print("Bakiyesi : $bakiye");
  print("Dogum Günü : $dogumGunu");
  print("Maaşı : $maas");
  print("Medeni Durumu : $medeniDurumu");
  print("Ürünün Yorumu : $urunYorumu");
  print("Ödeme Tarihi : $odemeTarihi");
  print("Ödeme  : $odeme");
  print("Sipariş Adeti  : $siparisAdeti");
  print("Araba Modeli  : $arabaModeli");
  print("Kitab'ın Adı  : $kitapAdi");
  print("Yayınlama Tarihi  : $yayinlanmaTarihi");
  print("İndirim Miktarı  : $indirimMiktari");
  print("Oda Sayısı  : $odaSayisi");
  print("Enlem  : $enlem");
  print("Boylam  : $boylam");
  print("Ürün Adı  : $urunAdi");
  print("Yemek Fiyatı  : $yemekFiyati");
  print("Marka  : $marka");
  print("Müzik Adı  : $muzikAdi");
  print("Video Süresi  : $videoSuresi");
  print("Ürün Puanı  : $urunPuani");
  print("Resim Adı  : $resimAdi");
  print("Dosya Formatı  : $dosyaFormati");
  print("Renk  : $renk");
  print("Renk Kodu : $renkKodu");
  print("Telefon Modeli : $telefonModeli");
  print("Ekran Boyutu : $ekranBoyutu");
  print("Ağırlık : $agirlik");
  print("Ulusal Gün : $ulusalGun");
  print("Tatil Günü : $tatilGunu");
  print("Rezervasyon Tarihi : $rezervasyonTarihi");
  print("Stok Adı : $stokAdi");
  print("Otobüs Hattı : $otobusHatti");
  print("Kalan Dakkika : $kalanDakkika");
  print("Takip Kodu : $takipKodu");
  print("Kupon Süresi : $kuponSuresi");
  print("Kupon Kodu : $kuponKodu");
  print("Fatura Adresi : $faturaAdresi");
  /* Değişkenler Ödev 1 */
}